// Canonical product copy shared by the alternative design
// directions (versions/b, versions/c). The baseline build (index01.html) keeps
// its own js/i18n.js and js/portfolio.js untouched; this module is the single
// source of truth for everything built after it, so copy edits land once
// instead of three times. Portfolio case-study data lives in portfolio-data.js.
//
// Voice: first person singular throughout. AnomInsight is one identifiable
// person (see PRODUCT.md, Product Principles 2), so the site says "I", never
// the corporate "we" the older markup fell back on.

export const CONTACT = {
  email: 'hello@anominsight.com',
  formspree: 'https://formspree.io/f/xjykwlyk',
  calendar: 'https://calendar.app.google/ckrBNEpqXD8Vm8Ji6',
  linkedin: 'https://www.linkedin.com/in/bence-csomor-923a8b3b2/',
  github: 'https://github.com/AnomInsight',
};

export const translations = {
  en: {
    'nav.overview': 'Overview',
    'nav.services': 'Services',
    'nav.projects': 'Projects',
    'nav.method': 'How it works',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'lang.switchTo': 'EN',
    'lang.switchAria': 'Switch to Hungarian',
    'home.pageTitle': 'AnomInsight – AI analytics and anomaly detection for industry',
    'a11y.skip': 'Skip to content',
    'a11y.menu': 'Menu',
    'a11y.primaryNav': 'Main navigation',
    'a11y.newTab': 'Opens in a new tab',

    // Two clauses, rendered as two line groups in the h1.
    'hero.heading': 'See what your data is hiding.',
    'hero.copy': 'I help companies understand their data, detect anomalies, and predict future outcomes using modern machine learning and interactive dashboards.',
    'hero.ctaPrimary': 'Get a free data audit',
    'hero.ctaSecondary': 'Book a call',
    'hero.scopeLabel': 'Focus',
    'hero.scopeValue': 'Manufacturing and industrial operations',
    'hero.preparedLabel': 'Practice',
    'hero.preparedValue': 'Bence Csomor, founder',
    'hero.basisLabel': 'Evidence',
    'hero.basisValue': 'Three case studies, public source code',
    'hero.callNote': 'You speak with me directly – 30 minutes, no obligation.',
    // Hero figure: a schematic example, captioned as one.
    'hero.signal.chartAria': 'Line chart: a torque reading stays inside its expected range, then one reading breaks out of it and is flagged as an anomaly.',
    'hero.signal.band': 'Expected range',
    'hero.signal.anomalyKey': 'Anomaly',
    'hero.signal.anomaly': 'Torque breaks out of its expected range.',
    'hero.signal.insightKey': 'Insight',
    'hero.signal.insight': 'Early tool wear – plan a tool change before the next shift.',
    'hero.signal.caption': 'Illustrative example – CNC machine torque',

    'proof.heading': 'Measured results',
    'proof.note': 'Every figure below comes from the case study linked beside it. Nothing here is a projection.',
    'proof.recall.value': '96%',
    'proof.recall.label': 'of real CNC failures caught in testing',
    'proof.recall.source': 'Predictive maintenance model',
    'proof.accuracy.value': '99.27%',
    'proof.accuracy.label': 'best-model accuracy on handwritten digits',
    'proof.accuracy.source': 'Digit classification study',
    'proof.experience.value': '4+',
    'proof.experience.label': 'years working with production and industrial data',
    'proof.experience.source': 'Practice to date',
    'proof.repos.value': '3',
    'proof.repos.label': 'case studies published with public source code',
    'proof.repos.source': 'github.com/AnomInsight',

    'problem.title': 'Most companies have data – but no clarity',
    'problem.text': 'Businesses collect large amounts of data every day, but struggle to turn it into actionable insights. Errors, inconsistencies, and hidden patterns often go unnoticed.',
    'problem.issue1': 'Unexpected downtime',
    'problem.issue1.detail': 'Machines fail without warning and production stops mid-shift.',
    'problem.issue2': 'Revenue loss from inefficiencies',
    'problem.issue2.detail': 'Waste and rework stay invisible because nobody measures them.',
    'problem.issue3': 'Poor forecasting',
    'problem.issue3.detail': 'Planning runs on last year\'s spreadsheet and a gut feeling.',
    'problem.issue4': 'Slow decision-making',
    'problem.issue4.detail': 'The number you need takes three days and two people to produce.',

    'solution.title': 'I turn raw data into actionable intelligence',
    'solution.text': 'I analyse your data and transform it into clear, interactive insights that help you make better decisions faster.',
    'solution.feature1': 'Data engineering',
    'solution.feature2': 'Machine learning',
    'solution.feature3': 'Visualisation',
    'solution.feature4': 'Predictive analytics',

    'services.heading': 'Core services',
    'services.subtitle': 'Where most engagements start.',
    'services.cta': 'Get a free data audit',
    'services.card1.title': 'Data audit and quality assessment',
    'services.card1.text': 'I analyse your datasets to identify missing values, inconsistencies, and structural issues.',
    'services.card2.title': 'Interactive dashboards',
    'services.card2.text': 'Custom dashboards with real-time charts and KPIs for full business visibility.',
    'services.card3.title': 'Automated reporting',
    'services.card3.text': 'Scheduled PDF or email reports summarising key insights and performance metrics.',
    'services.ctaAll': 'See all service packages',
    'capabilities.heading': 'What I deliver',
    'capabilities.text': 'Most engagements start with a data audit, dashboards or reporting. Anomaly detection, forecasting and predictive maintenance are built on request, around your data.',

    // The free entry offer is the discovery call (decided 2026-09-24); the data
    // audit is a quoted package. Version A uses these; b/c still carry the
    // older free-audit keys above.
    'offer.discoveryCta': 'Book a free discovery call',
    'offer.servicesCta': 'See services and packages',
    'offer.title': 'What the free discovery call covers',
    'offer.text': 'A free 30-minute call to understand your problem – no obligation.',
    'offer.item1': 'Your problem, your data sources, and what a useful result would look like',
    'offer.item2': 'An honest view of whether data analysis or machine learning is the right tool for it',
    'offer.item3': 'A recommended next step and, if it fits, a custom quote',

    // services.html. No fixed prices anywhere: every paid package is quoted.
    'packages.pageTitle': 'Services – AnomInsight',
    'packages.heading': 'Service packages, scoped to your data',
    'packages.intro': 'Most packages deliver reports and dashboard views, and the underlying code and methodology stay with me. If you need the solution running inside your own systems, Integrated Implementation hands it over to you.',
    'packages.quoteNote': 'There is no fixed price list: every package is scoped to your data and quoted individually.',
    'packages.featured': 'Featured',
    'packages.quoteCta': 'Get a custom quote',
    'packages.quoteMessage': 'I would like a custom quote for: {package}.',
    'packages.discovery.title': 'Free Discovery Call',
    'packages.discovery.meta': '30 minutes · Free',
    'packages.discovery.text': 'A free 30-minute call to understand your problem – no obligation.',
    'packages.audit.title': 'Data Audit',
    'packages.audit.meta': 'One-off · PDF/PPT report',
    'packages.audit.text': 'Exploratory data analysis, data quality assessment, and a recommendations package – delivered as a PDF/PPT report.',
    'packages.project.title': 'One-off Project Delivery',
    'packages.project.meta': 'One-off · Dashboard walkthrough + report',
    'packages.project.text': 'A custom ML model, anomaly detection, or automation solution built for your specific problem. Includes a dashboard walkthrough and a written report reflecting the data at delivery time – the code and pipeline are not handed over.',
    // Marketing copy only: the client gets rights to the project-specific
    // solution; general reusable components stay reusable by me. Never word
    // this as full/exclusive ownership of all code (contract defines terms).
    'packages.integrated.title': 'Integrated Implementation (Full Handover)',
    'packages.integrated.badge': 'Most complete',
    'packages.integrated.meta': 'One-off · Deployment-ready solution + integration support',
    'packages.integrated.text': 'You receive a complete, deployment-ready solution that can be integrated directly into your production or operational systems. You receive the necessary rights to use the project-specific solution; general-purpose, reusable code components, methodologies, and technical approaches remain available for reuse by the provider in other projects.',
    'packages.monitoring.title': 'Ongoing Monitoring & Reporting',
    'packages.monitoring.meta': 'Weekly or monthly · report + 30-min review',
    'packages.monitoring.text': 'Weekly or monthly data refresh, an updated dashboard view, a PDF report, and a 30-minute review meeting each cycle – for continuous, up-to-date visibility.',

    'advanced.title': 'Advanced analytics',
    'advanced.subtitle': 'Available on request',
    'advanced.card1.title': 'Anomaly detection',
    'advanced.card1.text': 'Automatically detect unusual patterns in your operational or business data.',
    'advanced.card2.title': 'Forecasting models',
    'advanced.card2.text': 'Predict future trends in sales, production, or operational metrics.',
    'advanced.card3.title': 'Predictive maintenance',
    'advanced.card3.text': 'Identify potential failures before they happen using historical and real-time data.',

    'portfolio.heading': 'Selected projects',
    'portfolio.subtitle': 'Real projects, with real results and public source code.',
    'portfolio.note': 'Every project links to its public repository, so you can inspect the actual work.',
    'portfolio.statusFiltersTitle': 'Browse by status',
    'portfolio.filtersTitle': 'Refine by type',
    'portfolio.filtersAria': 'Project type filters, select one or more',
    'portfolio.statusFiltersAria': 'Project status filters, select one or more',
    'portfolio.statsAria': 'Portfolio highlights',
    'portfolio.trackAria': 'Portfolio projects',
    'portfolio.navAria': 'Portfolio navigation',
    'portfolio.navPrev': 'Previous project',
    'portfolio.navNext': 'Next project',
    'portfolio.pauseRotation': 'Pause automatic rotation',
    'portfolio.navDotsAria': 'Project pages',
    'portfolio.filterAll': 'All',
    'portfolio.clearAllFilters': 'Clear all filters',
    'portfolio.empty': 'No projects match these filters yet.',
    'portfolio.expand': 'Read the full overview',
    'portfolio.collapse': 'Close the overview',
    'portfolio.githubLabel': 'View source on GitHub',
    'portfolio.githubButton': 'View on GitHub',
    'portfolio.detailsClose': 'Close',
    'portfolio.metaPrefix': 'Types',
    'portfolio.focusHint': 'Click any card to bring it to focus.',
    'portfolio.navDotLabel': 'Go to project {n}',
    'portfolio.statLabelProjects': 'Case studies published',
    'portfolio.statLabelIndustries': 'Industries covered',
    'portfolio.statLabelRepos': 'Public repositories',
    'portfolio.statLabelTypes': 'Solution types',
    'portfolio.ctaText': 'Have a similar challenge in your operation?',
    'portfolio.ctaButton': 'Let\'s talk',

    'method.title': 'How it works',
    'method.subtitle': 'Four steps from raw export to a decision you can act on.',
    'method.step1.title': 'Data input',
    'method.step1.text': 'Upload your Excel file or connect your database (SQL / API).',
    'method.step2.title': 'Analysis',
    'method.step2.text': 'I process and clean your data using advanced analytics and ML models.',
    'method.step3.title': 'Insights',
    'method.step3.text': 'You receive dashboards, reports, and actionable recommendations.',
    'method.step4.title': 'Continuous improvement',
    'method.step4.text': 'Optional ongoing monitoring and model updates.',

    'usecases.title': 'Who this is for',
    'usecases.subtitle': 'The work started in manufacturing. The methods travel.',
    'usecases.item1': 'Manufacturing companies',
    'usecases.item2': 'Logistics and supply chain businesses',
    'usecases.item3': 'E-commerce companies',
    'usecases.item4': 'Energy and utilities',
    'usecases.item5': 'Any data-driven organisation',

    'value.title': 'What you gain',
    'value.item1': 'Better decision-making',
    'value.item2': 'Reduced operational costs',
    'value.item3': 'Early detection of problems',
    'value.item4': 'Clear visibility into business performance',
    'value.item5': 'Data-driven strategy instead of guesswork',

    'roadmap.title': 'Platform evolution',
    'roadmap.subtitle': 'I am continuously expanding what the practice can deliver.',
    'roadmap.available': 'Currently available',
    'roadmap.developing': 'In development',
    'roadmap.item1': 'Data audit',
    'roadmap.item2': 'Dashboards',
    'roadmap.item3': 'Automated reporting',
    'roadmap.item4': 'Real-time anomaly detection',
    'roadmap.item5': 'Predictive analytics',
    'roadmap.item6': 'API integrations (SQL, ERP, IoT)',

    'about.title': 'Who you are working with',
    'about.name': 'Bence Csomor',
    'about.role': 'Founder and data scientist',
    'about.bio1': 'AnomInsight is a one-person practice. Every audit, model and dashboard is built and delivered by me, so there is no account layer between you and the person doing the work.',
    'about.bio2': 'I have spent four years and more working with production and industrial data, and I publish what I build: every case study on this page links to a public repository you can read, run, and judge for yourself.',
    'about.linkedin': 'LinkedIn profile',
    'about.github': 'GitHub organisation',
    'about.initials': 'BC',

    'finalcta.title': 'What is included in your free data audit',
    'finalcta.text': 'A quick, no-obligation look at your data before you commit to anything.',
    'finalcta.item1': 'Data quality check: missing values, inconsistencies, and structural issues',
    'finalcta.item2': 'A short written summary of key findings and quick-win recommendations',
    'finalcta.item3': 'A follow-up call to walk through the results together',
    'finalcta.note': 'No long-term commitment required.',
    'finalcta.cta': 'Get a free data audit',

    'contact.heading': 'Get in touch',
    'contact.copy': 'Have questions? Fill out the form and I will get back to you within 24 hours, or reach me directly by email.',
    'contact.emailLabel': 'Email',
    'contact.locationLabel': 'Location',
    'contact.locationValue': 'Remote / worldwide',
    'contact.responseLabel': 'Response time',
    'contact.responseValue': 'Within 24 hours',
    'contact.bookCallButton': 'Book a call',
    'contact.formHeading': 'Send me a message',
    'contact.formName': 'Name',
    'contact.formNamePlaceholder': 'Your name',
    'contact.formEmail': 'Email',
    'contact.formEmailPlaceholder': 'you@company.com',
    'contact.formMessage': 'Message',
    'contact.formMessagePlaceholder': 'Tell me about your data and what you need from it',
    'contact.formSubmit': 'Send message',
    'contact.formSending': 'Sending…',
    'contact.formSuccess': 'Thanks – your message has been sent. I will get back to you within 24 hours.',
    'contact.formError': 'Something went wrong. Please email me directly at hello@anominsight.com.',

    'footer.tagline': 'AI-powered data analytics for modern businesses.',
    'footer.rights': 'All rights reserved.',
  },

  hu: {
    'nav.overview': 'Áttekintés',
    'nav.services': 'Szolgáltatások',
    'nav.projects': 'Projektek',
    'nav.method': 'Hogyan működik',
    'nav.about': 'Rólam',
    'nav.contact': 'Kapcsolat',
    'lang.switchTo': 'HU',
    'lang.switchAria': 'Váltás angol nyelvre',
    'home.pageTitle': 'AnomInsight – MI-alapú adatelemzés és anomáliafelismerés',
    'a11y.skip': 'Ugrás a tartalomra',
    'a11y.menu': 'Menü',
    'a11y.primaryNav': 'Fő navigáció',
    'a11y.newTab': 'Új lapon nyílik meg',

    'hero.heading': 'Lásd meg, amit az adataid elrejtenek.',
    'hero.copy': 'Segítek a vállalatoknak megérteni az adataikat, felismerni az anomáliákat és előre jelezni a várható alakulásokat modern gépi tanulási módszerekkel és interaktív adatvizualizációval.',
    'hero.ctaPrimary': 'Ingyenes adataudit kérése',
    'hero.ctaSecondary': 'Időpont foglalása',
    'hero.scopeLabel': 'Fókusz',
    'hero.scopeValue': 'Gyártás és ipari működés',
    'hero.preparedLabel': 'Praxis',
    'hero.preparedValue': 'Csomor Bence, alapító',
    'hero.basisLabel': 'Bizonyíték',
    'hero.basisValue': 'Három esettanulmány, nyilvános forráskóddal',
    'hero.callNote': 'Közvetlenül velem beszélsz – 30 perc, kötelezettség nélkül.',
    'hero.signal.chartAria': 'Vonaldiagram: a nyomaték a várható tartományon belül mozog, majd egy mérés kilép belőle, és a rendszer anomáliaként jelöli.',
    'hero.signal.band': 'Várható tartomány',
    'hero.signal.anomalyKey': 'Anomália',
    'hero.signal.anomaly': 'A nyomaték kilép a várható tartományból.',
    'hero.signal.insightKey': 'Meglátás',
    'hero.signal.insight': 'Kezdődő szerszámkopás – a cserét érdemes a következő műszak előtt betervezni.',
    'hero.signal.caption': 'Szemléltető példa – CNC-gép nyomatéka',

    'proof.heading': 'Mért eredmények',
    'proof.note': 'Az alábbi számok mind a mellettük hivatkozott esettanulmányból származnak. Egyik sem becslés.',
    'proof.recall.value': '96%',
    'proof.recall.label': 'meghibásodások felismerési aránya a tesztadatokon',
    'proof.recall.source': 'Prediktív karbantartási modell',
    'proof.accuracy.value': '99,27%',
    'proof.accuracy.label': 'a legjobb modell pontossága kézzel írt számjegyek felismerésében',
    'proof.accuracy.source': 'Számjegyfelismerési kutatás',
    'proof.experience.value': '4+',
    'proof.experience.label': 'év tapasztalat termelési és ipari adatokkal',
    'proof.experience.source': 'Eddigi tapasztalat',
    'proof.repos.value': '3',
    'proof.repos.label': 'esettanulmány nyilvános forráskóddal publikálva',
    'proof.repos.source': 'github.com/AnomInsight',

    'problem.title': 'A legtöbb cégnél van adat – de nincs tisztánlátás',
    'problem.text': 'A vállalatok naponta nagy mennyiségű adatot gyűjtenek, mégis nehezen alakítják át ezeket valóban hasznos, döntést támogató információvá. A hibák, az eltérések és a rejtett mintázatok gyakran észrevétlenek maradnak.',
    'problem.issue1': 'Váratlan leállások',
    'problem.issue1.detail': 'A gépek előjel nélkül meghibásodhatnak, és leállhat a termelés a műszak közben.',
    'problem.issue2': 'Hatékonysági problémákból eredő bevételkiesés',
    'problem.issue2.detail': 'A selejt és az újramunkálás rejtve marad, mert senki sem méri őket.',
    'problem.issue3': 'Pontatlan előrejelzés',
    'problem.issue3.detail': 'A tervezés a tavalyi táblázatra és megérzésre épül.',
    'problem.issue4': 'Lassú döntéshozatal',
    'problem.issue4.detail': 'Egyetlen szám előállítása három napba és két ember munkájába kerül.',

    'solution.title': 'A nyers adatokból döntést támogató információt készítek',
    'solution.text': 'Elemzem az adataidat, és átlátható, interaktív formában mutatom meg a bennük rejlő összefüggéseket, hogy gyorsabb és megalapozottabb döntéseket hozhass.',
    'solution.feature1': 'Adatmérnökség',
    'solution.feature2': 'Gépi tanulás',
    'solution.feature3': 'Vizualizáció',
    'solution.feature4': 'Prediktív analitika',

    'services.heading': 'Fő szolgáltatások',
    'services.subtitle': 'A legtöbb együttműködés itt kezdődik.',
    'services.cta': 'Ingyenes adataudit kérése',
    'services.card1.title': 'Adataudit és minőségértékelés',
    'services.card1.text': 'Átnézem az adathalmazaidat, és azonosítom a hiányzó értékeket, az ellentmondásokat és a szerkezeti hibákat.',
    'services.card2.title': 'Interaktív dashboardok',
    'services.card2.text': 'Egyedi dashboardok valós idejű diagramokkal és KPI-okkal, hogy átlásd az üzleti teljesítményt.',
    'services.card3.title': 'Automatizált riportálás',
    'services.card3.text': 'Ütemezett PDF- vagy e-mail-riportok a legfontosabb megállapításokkal és mutatókkal.',
    'services.ctaAll': 'Az összes szolgáltatáscsomag',
    'capabilities.heading': 'Amiben segíteni tudok',
    'capabilities.text': 'A legtöbb együttműködés adataudittal, dashboardokkal vagy riportálással kezdődik. Az anomáliafelismerést, az előrejelzést és a prediktív karbantartást kérésre, a te adataidra szabva építem meg.',

    'offer.discoveryCta': 'Ingyenes discovery call foglalása',
    'offer.servicesCta': 'Szolgáltatások és csomagok',
    'offer.title': 'Miről szól az ingyenes discovery call',
    'offer.text': '30 perces beszélgetés a problémád felmérésére – nincs kötelezettség.',
    'offer.item1': 'A problémád, az adatforrásaid, és hogy számodra mi lenne a hasznos eredmény',
    'offer.item2': 'Őszinte vélemény arról, hogy az adatelemzés vagy a gépi tanulás valóban jó eszköz-e rá',
    'offer.item3': 'Javasolt következő lépés, és ha illik hozzád, egyedi ajánlat',

    'packages.pageTitle': 'Szolgáltatások – AnomInsight',
    // Soft hyphen: lets the long compound break cleanly on narrow phones.
    'packages.heading': 'Szolgáltatás­csomagok, a te adataidra szabva',
    'packages.intro': 'A legtöbb csomag riportot és dashboard-nézetet biztosít – a mögöttes kód és módszertan nálam marad. Ha a megoldást a saját rendszeredben szeretnéd futtatni, az Integrált Megvalósítás teljes átadással jár.',
    'packages.quoteNote': 'Fix árlista nincs: minden csomagot a te adataidhoz igazítok, és egyedi ajánlatot adok rá.',
    'packages.featured': 'Kiemelt',
    'packages.quoteCta': 'Egyedi ajánlatért írj',
    'packages.quoteMessage': 'Egyedi ajánlatot kérnék erre a csomagra: {package}.',
    'packages.discovery.title': 'Ingyenes Discovery Call',
    'packages.discovery.meta': '30 perc · Ingyenes',
    'packages.discovery.text': '30 perces beszélgetés a problémád felmérésére – nincs kötelezettség.',
    'packages.audit.title': 'Adat Audit',
    'packages.audit.meta': 'Egyszeri · PDF/PPT riport',
    'packages.audit.text': 'Adatfeltárás (EDA), adatminőség-felmérés és javaslatcsomag – PDF/PPT riport formájában.',
    'packages.project.title': 'Egyszeri Projektmegvalósítás',
    'packages.project.meta': 'Egyszeri · Dashboard-bemutató + riport',
    'packages.project.text': 'Egyedi ML modell, anomália-detektálás vagy automatizálás a te problémádra szabva. Dashboard-bemutató és írásos riport a leszállításkori adatállapotra – a kód és a pipeline nem kerül átadásra.',
    'packages.integrated.title': 'Integrált Megvalósítás (teljes átadással)',
    'packages.integrated.badge': 'Legteljesebb',
    'packages.integrated.meta': 'Egyszeri · Üzembe helyezhető megoldás + integrációs támogatás',
    'packages.integrated.text': 'Teljes, üzembe helyezésre kész megoldást kapsz, amelyet közvetlenül beépíthetsz a saját gyártási vagy üzemi rendszeredbe. A projekt-specifikus megoldás felhasználási joga az ügyfelet illeti; az általános, újrafelhasználható kódelemek, módszertanok és technikai megoldások azonban továbbra is a szolgáltató által más projektekben is felhasználhatók.',
    'packages.monitoring.title': 'Rendszeres Monitoring & Reporting',
    'packages.monitoring.meta': 'Heti vagy havi · PDF riport + 30 perces review',
    'packages.monitoring.text': 'Heti vagy havi adatfrissítés, frissített dashboard-nézet, PDF riport és ciklusonként 30 perces review meeting – a folyamatos, friss rálátásért.',

    'advanced.title': 'Haladó analitika',
    'advanced.subtitle': 'Kérésre elérhető',
    'advanced.card1.title': 'Anomáliafelismerés',
    'advanced.card1.text': 'Automatikusan felismeri a szokatlan mintázatokat a működési vagy üzleti adataidban.',
    'advanced.card2.title': 'Előrejelző modellek',
    'advanced.card2.text': 'Előre jelzi az értékesítés, a termelés vagy a működési mutatók várható alakulását.',
    'advanced.card3.title': 'Prediktív karbantartás',
    'advanced.card3.text': 'Történeti és valós idejű adatokból jelzi a várható meghibásodásokat, mielőtt bekövetkeznének.',

    'portfolio.heading': 'Kiemelt projektek',
    'portfolio.subtitle': 'Valódi projektek, valós eredményekkel és nyilvános forráskóddal.',
    'portfolio.note': 'Minden projekt a nyilvános GitHub-repójára mutat, így magad is megnézheted a munkát.',
    'portfolio.statusFiltersTitle': 'Szűrés státusz szerint',
    'portfolio.filtersTitle': 'Szűrés típus szerint',
    'portfolio.filtersAria': 'Projekttípus-szűrők, egy vagy több típus választható',
    'portfolio.statusFiltersAria': 'Projektstátusz-szűrők, egy vagy több választható',
    'portfolio.statsAria': 'Portfólió kiemelt számok',
    'portfolio.trackAria': 'Portfólió projektek',
    'portfolio.navAria': 'Portfólió navigáció',
    'portfolio.navPrev': 'Előző projekt',
    'portfolio.navNext': 'Következő projekt',
    'portfolio.pauseRotation': 'Automatikus léptetés szüneteltetése',
    'portfolio.navDotsAria': 'Projekt oldalak',
    'portfolio.filterAll': 'Összes',
    'portfolio.clearAllFilters': 'Szűrők törlése',
    'portfolio.empty': 'Ezekkel a szűrőkkel még nincs találat.',
    'portfolio.expand': 'Teljes áttekintés elolvasása',
    'portfolio.collapse': 'Áttekintés bezárása',
    'portfolio.githubLabel': 'Forráskód megtekintése GitHubon',
    'portfolio.githubButton': 'Megtekintés GitHubon',
    'portfolio.detailsClose': 'Bezárás',
    'portfolio.metaPrefix': 'Típusok',
    'portfolio.focusHint': 'Kattints egy kártyára a részletek megtekintéséhez.',
    'portfolio.navDotLabel': 'Ugrás a(z) {n}. projekthez',
    'portfolio.statLabelProjects': 'Publikált esettanulmányok',
    'portfolio.statLabelIndustries': 'Lefedett iparágak',
    'portfolio.statLabelRepos': 'Nyilvános repók',
    'portfolio.statLabelTypes': 'Megoldástípusok',
    'portfolio.ctaText': 'Hasonló kihívással nézel szembe a saját működésedben?',
    'portfolio.ctaButton': 'Beszéljünk',

    'method.title': 'Hogyan működik',
    'method.subtitle': 'Négy lépés a nyers adatoktól a megalapozott döntésig.',
    'method.step1.title': 'Adatbevitel',
    'method.step1.text': 'Töltsd fel az Excel-fájlt, vagy csatlakoztasd az adatbázist (SQL / API).',
    'method.step2.title': 'Elemzés',
    'method.step2.text': 'Feldolgozom és megtisztítom az adatokat fejlett elemzési módszerekkel és gépi tanulási modellekkel.',
    'method.step3.title': 'Eredmények',
    'method.step3.text': 'Dashboardokat, riportokat és konkrét javaslatokat kapsz.',
    'method.step4.title': 'Folyamatos fejlesztés',
    'method.step4.text': 'Opcionális folyamatos monitorozás és modellfrissítés.',

    'usecases.title': 'Kinek szól',
    'usecases.subtitle': 'A munka a gyártásban kezdődött. A módszerek más iparágakban is alkalmazhatók.',
    'usecases.item1': 'Gyártó vállalatok',
    'usecases.item2': 'Logisztikai és ellátási lánccal foglalkozó vállalatok',
    'usecases.item3': 'E-kereskedelmi cégek',
    'usecases.item4': 'Energetika és közművek',
    'usecases.item5': 'Bármely adatvezérelt szervezet',

    'value.title': 'Mit nyersz vele',
    'value.item1': 'Megalapozottabb döntések',
    'value.item2': 'Alacsonyabb működési költség',
    'value.item3': 'A problémák korai felismerése',
    'value.item4': 'Átláthatóbb kép az üzleti teljesítményről',
    'value.item5': 'Adatvezérelt stratégia találgatás helyett',

    'roadmap.title': 'Folyamatosan bővülő szolgáltatások',
    'roadmap.subtitle': 'Folyamatosan bővítem az elérhető szolgáltatásokat és megoldásokat.',
    'roadmap.available': 'Jelenleg elérhető',
    'roadmap.developing': 'Fejlesztés alatt',
    'roadmap.item1': 'Adataudit',
    'roadmap.item2': 'Dashboardok',
    'roadmap.item3': 'Automatizált riportálás',
    'roadmap.item4': 'Valós idejű anomáliafelismerés',
    'roadmap.item5': 'Prediktív analitika',
    'roadmap.item6': 'API-integrációk (SQL, ERP, IoT)',

    'about.title': 'Kivel dolgozol együtt',
    'about.name': 'Csomor Bence',
    'about.role': 'Alapító és data scientist',
    'about.bio1': 'Az AnomInsight egyszemélyes vállalkozás. Minden auditot, modellt és dashboardot én készítek és adok át, így közvetlenül azzal dolgozol, aki a munkát végzi.',
    'about.bio2': 'Több mint négy éve dolgozom termelési és ipari adatokkal, és publikálom, amit építek: az oldalon szereplő minden esettanulmány egy nyilvános repóra mutat, amelyeket elolvashatsz, lefuttathatsz és saját magad is értékelhetsz.',
    'about.linkedin': 'LinkedIn-profil',
    'about.github': 'GitHub-szervezet',
    'about.initials': 'CS',

    'finalcta.title': 'Mit tartalmaz az ingyenes adataudit',
    'finalcta.text': 'Gyors, kötelezettségmentes betekintés az adataidba, mielőtt bármilyen együttműködés mellett döntenél.',
    'finalcta.item1': 'Adatminőség-ellenőrzés: hiányzó értékek, ellentmondások és szerkezeti hibák',
    'finalcta.item2': 'Rövid írásos összefoglaló a fő megállapításokról és a gyorsan megvalósítható fejlesztési lehetőségekről',
    'finalcta.item3': 'Egy utólagos egyeztetés, amelyen közösen átbeszéljük az eredményeket',
    'finalcta.note': 'Hosszú távú elköteleződés nélkül.',
    'finalcta.cta': 'Ingyenes adataudit kérése',

    'contact.heading': 'Lépj kapcsolatba velem',
    'contact.copy': 'Kérdésed van? Töltsd ki az űrlapot, és 24 órán belül válaszolok, vagy írj közvetlenül e-mailben.',
    'contact.emailLabel': 'E-mail',
    'contact.locationLabel': 'Helyszín',
    'contact.locationValue': 'Távoli együttműködés / világszerte',
    'contact.responseLabel': 'Válaszidő',
    'contact.responseValue': '24 órán belül',
    'contact.bookCallButton': 'Időpont foglalása',
    'contact.formHeading': 'Írj nekem üzenetet',
    'contact.formName': 'Név',
    'contact.formNamePlaceholder': 'A neved',
    'contact.formEmail': 'E-mail',
    'contact.formEmailPlaceholder': 'te@ceged.hu',
    'contact.formMessage': 'Üzenet',
    'contact.formMessagePlaceholder': 'Írd le, milyen adatokkal rendelkezel, és mit szeretnél megtudni belőlük',
    'contact.formSubmit': 'Üzenet küldése',
    'contact.formSending': 'Küldés…',
    'contact.formSuccess': 'Köszönöm – az üzeneted sikeresen elküldve. 24 órán belül válaszolok.',
    'contact.formError': 'Hiba történt. Kérlek írj közvetlenül a hello@anominsight.com címre.',

    'footer.tagline': 'MI-alapú adatelemzés modern vállalatoknak.',
    'footer.rights': 'Minden jog fenntartva.',
  },
};
