// Canonical product copy and portfolio data shared by the alternative design
// directions (versions/b, versions/c). The baseline build (index01.html) keeps
// its own js/i18n.js and js/portfolio.js untouched; this module is the single
// source of truth for everything built after it, so copy edits land once
// instead of three times.
//
// Voice: first person singular throughout. AnomInsight is one identifiable
// person (see PRODUCT.md, Product Principles 2), so the site says "I", never
// the corporate "we" the older markup fell back on.

export const CONTACT = {
  email: 'hello@anominsight.com',
  formspree: 'https://formspree.io/f/xjykwlyk',
  calendar: 'https://calendar.app.google/ckrBNEpqXD8Vm8Ji6',
  linkedin: 'https://www.linkedin.com/in/bence-csomor-923a8b3b2/',
  github: 'https://github.com/AnomInsight',
};

export const translations = {
  en: {
    'nav.overview': 'Overview',
    'nav.services': 'Services',
    'nav.projects': 'Projects',
    'nav.method': 'How it works',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'lang.switchTo': 'HU',
    'lang.switchAria': 'Switch to Hungarian',

    'hero.heading': 'AI-powered analytics that turn data into decisions',
    'hero.copy': 'I help companies understand their data, detect anomalies, and predict future outcomes using modern machine learning and interactive dashboards.',
    'hero.ctaPrimary': 'Get a free data audit',
    'hero.ctaSecondary': 'Book a call',
    'hero.scopeLabel': 'Focus',
    'hero.scopeValue': 'Manufacturing and industrial operations',
    'hero.preparedLabel': 'Practice',
    'hero.preparedValue': 'Bence Csomor, founder',
    'hero.basisLabel': 'Evidence',
    'hero.basisValue': 'Three case studies, public source code',

    'proof.heading': 'Measured results',
    'proof.note': 'Every figure below comes from the case study linked beside it. Nothing here is a projection.',
    'proof.recall.value': '96%',
    'proof.recall.label': 'of real CNC failures caught in testing',
    'proof.recall.source': 'Predictive maintenance model',
    'proof.accuracy.value': '99.27%',
    'proof.accuracy.label': 'best-model accuracy on handwritten digits',
    'proof.accuracy.source': 'Digit classification study',
    'proof.experience.value': '4+',
    'proof.experience.label': 'years working with production and industrial data',
    'proof.experience.source': 'Practice to date',
    'proof.repos.value': '3',
    'proof.repos.label': 'case studies published with public source code',
    'proof.repos.source': 'github.com/AnomInsight',

    'credentials.item1.title': '4+ years',
    'credentials.item1.text': 'Working with production and industrial data',
    'credentials.item2.title': 'Industrial focus',
    'credentials.item2.text': 'Manufacturing process analytics',
    'credentials.item3.title': 'Proven results',
    'credentials.item3.text': 'Real case studies with measurable outcomes, published on GitHub',
    'credentials.item4.title': 'Continuous development',
    'credentials.item4.text': 'New analytics capabilities in active development',

    'problem.title': 'Most companies have data — but no clarity',
    'problem.text': 'Businesses collect large amounts of data every day, but struggle to turn it into actionable insights. Errors, inconsistencies, and hidden patterns often go unnoticed.',
    'problem.issue1': 'Unexpected downtime',
    'problem.issue1.detail': 'Machines fail without warning and production stops mid-shift.',
    'problem.issue2': 'Revenue loss from inefficiencies',
    'problem.issue2.detail': 'Waste and rework stay invisible because nobody measures them.',
    'problem.issue3': 'Poor forecasting',
    'problem.issue3.detail': 'Planning runs on last year\'s spreadsheet and a gut feeling.',
    'problem.issue4': 'Slow decision-making',
    'problem.issue4.detail': 'The number you need takes three days and two people to produce.',

    'solution.title': 'I turn raw data into actionable intelligence',
    'solution.text': 'I analyse your data and transform it into clear, interactive insights that help you make better decisions faster.',
    'solution.feature1': 'Data engineering',
    'solution.feature2': 'Machine learning',
    'solution.feature3': 'Visualisation',
    'solution.feature4': 'Predictive analytics',

    'services.heading': 'Core services',
    'services.subtitle': 'Where most engagements start.',
    'services.cta': 'Get a free data audit',
    'services.card1.title': 'Data audit and quality assessment',
    'services.card1.text': 'I analyse your datasets to identify missing values, inconsistencies, and structural issues.',
    'services.card2.title': 'Interactive dashboards',
    'services.card2.text': 'Custom dashboards with real-time charts and KPIs for full business visibility.',
    'services.card3.title': 'Automated reporting',
    'services.card3.text': 'Scheduled PDF or email reports summarising key insights and performance metrics.',

    'advanced.title': 'Advanced analytics',
    'advanced.subtitle': 'Available on request',
    'advanced.card1.title': 'Anomaly detection',
    'advanced.card1.text': 'Automatically detect unusual patterns in your operational or business data.',
    'advanced.card2.title': 'Forecasting models',
    'advanced.card2.text': 'Predict future trends in sales, production, or operational metrics.',
    'advanced.card3.title': 'Predictive maintenance',
    'advanced.card3.text': 'Identify potential failures before they happen using historical and real-time data.',

    'portfolio.heading': 'Selected projects',
    'portfolio.subtitle': 'Real projects, with real results and public source code.',
    'portfolio.note': 'Every project links to its public repository, so you can inspect the actual work.',
    'portfolio.statusFiltersTitle': 'Browse by status',
    'portfolio.filtersTitle': 'Refine by type',
    'portfolio.filtersAria': 'Project type filters, select one or more',
    'portfolio.statusFiltersAria': 'Project status filters, select one or more',
    'portfolio.statsAria': 'Portfolio highlights',
    'portfolio.trackAria': 'Portfolio projects',
    'portfolio.navAria': 'Portfolio navigation',
    'portfolio.navPrev': 'Previous project',
    'portfolio.navNext': 'Next project',
    'portfolio.navDotsAria': 'Project pages',
    'portfolio.filterAll': 'All',
    'portfolio.clearAllFilters': 'Clear all filters',
    'portfolio.empty': 'No projects match these filters yet.',
    'portfolio.expand': 'Read the full overview',
    'portfolio.collapse': 'Close the overview',
    'portfolio.githubLabel': 'View source on GitHub',
    'portfolio.githubButton': 'View on GitHub',
    'portfolio.detailsClose': 'Close',
    'portfolio.metaPrefix': 'Types',
    'portfolio.focusHint': 'Click any card to bring it to focus.',
    'portfolio.navDotLabel': 'Go to project {n}',
    'portfolio.statLabelProjects': 'Case studies published',
    'portfolio.statLabelIndustries': 'Industries covered',
    'portfolio.statLabelRepos': 'Public repositories',
    'portfolio.ctaText': 'Have a similar challenge in your operation?',
    'portfolio.ctaButton': 'Let\'s talk',

    'method.title': 'How it works',
    'method.subtitle': 'Four steps from raw export to a decision you can act on.',
    'method.step1.title': 'Data input',
    'method.step1.text': 'Upload your Excel file or connect your database (SQL / API).',
    'method.step2.title': 'Analysis',
    'method.step2.text': 'I process and clean your data using advanced analytics and ML models.',
    'method.step3.title': 'Insights',
    'method.step3.text': 'You receive dashboards, reports, and actionable recommendations.',
    'method.step4.title': 'Continuous improvement',
    'method.step4.text': 'Optional ongoing monitoring and model updates.',

    'usecases.title': 'Who this is for',
    'usecases.subtitle': 'The work started in manufacturing. The methods travel.',
    'usecases.item1': 'Manufacturing companies',
    'usecases.item2': 'Logistics and supply chain businesses',
    'usecases.item3': 'E-commerce companies',
    'usecases.item4': 'Energy and utilities',
    'usecases.item5': 'Any data-driven organisation',

    'value.title': 'What you gain',
    'value.item1': 'Better decision-making',
    'value.item2': 'Reduced operational costs',
    'value.item3': 'Early detection of problems',
    'value.item4': 'Clear visibility into business performance',
    'value.item5': 'Data-driven strategy instead of guesswork',

    'roadmap.title': 'Platform evolution',
    'roadmap.subtitle': 'I am continuously expanding what the practice can deliver.',
    'roadmap.available': 'Currently available',
    'roadmap.developing': 'In development',
    'roadmap.item1': 'Data audit',
    'roadmap.item2': 'Dashboards',
    'roadmap.item3': 'Automated reporting',
    'roadmap.item4': 'Real-time anomaly detection',
    'roadmap.item5': 'Predictive analytics',
    'roadmap.item6': 'API integrations (SQL, ERP, IoT)',

    'about.title': 'Who you are working with',
    'about.name': 'Bence Csomor',
    'about.role': 'Founder and data scientist',
    'about.bio1': 'AnomInsight is a one-person practice. Every audit, model and dashboard is built and delivered by me, so there is no account layer between you and the person doing the work.',
    'about.bio2': 'I have spent four years and more working with production and industrial data, and I publish what I build: every case study on this page links to a public repository you can read, run, and judge for yourself.',
    'about.linkedin': 'LinkedIn profile',
    'about.github': 'GitHub organisation',
    'about.initials': 'BC',

    'finalcta.title': 'What is included in your free data audit',
    'finalcta.text': 'A quick, no-obligation look at your data before you commit to anything.',
    'finalcta.item1': 'Data quality check: missing values, inconsistencies, and structural issues',
    'finalcta.item2': 'A short written summary of key findings and quick-win recommendations',
    'finalcta.item3': 'A follow-up call to walk through the results together',
    'finalcta.note': 'No long-term commitment required.',
    'finalcta.cta': 'Get a free data audit',

    'contact.heading': 'Get in touch',
    'contact.copy': 'Have questions? Fill out the form and I will get back to you within 24 hours, or reach me directly by email.',
    'contact.emailLabel': 'Email',
    'contact.locationLabel': 'Location',
    'contact.locationValue': 'Remote / worldwide',
    'contact.responseLabel': 'Response time',
    'contact.responseValue': 'Within 24 hours',
    'contact.bookCallButton': 'Book a call',
    'contact.formHeading': 'Send me a message',
    'contact.formName': 'Name',
    'contact.formNamePlaceholder': 'Your name',
    'contact.formEmail': 'Email',
    'contact.formEmailPlaceholder': 'you@company.com',
    'contact.formMessage': 'Message',
    'contact.formMessagePlaceholder': 'Tell me about your data and what you need from it',
    'contact.formSubmit': 'Send message',
    'contact.formSending': 'Sending…',
    'contact.formSuccess': 'Thanks — your message has been sent. I will get back to you within 24 hours.',
    'contact.formError': 'Something went wrong. Please email me directly at hello@anominsight.com.',

    'footer.tagline': 'AI-powered data analytics for modern businesses.',
    'footer.rights': 'All rights reserved.',
  },

  hu: {
    'nav.overview': 'Áttekintés',
    'nav.services': 'Szolgáltatások',
    'nav.projects': 'Projektek',
    'nav.method': 'Hogyan működik',
    'nav.about': 'Rólam',
    'nav.contact': 'Kapcsolat',
    'lang.switchTo': 'EN',
    'lang.switchAria': 'Váltás angol nyelvre',

    'hero.heading': 'MI-alapú adatelemzés, amelyből jobb döntések születnek',
    'hero.copy': 'Segítek a vállalatoknak megérteni az adataikat, felismerni az anomáliákat és előre jelezni a várható alakulásokat modern gépi tanulási módszerekkel és interaktív adatvizualizációval.',
    'hero.ctaPrimary': 'Ingyenes adataudit kérése',
    'hero.ctaSecondary': 'Időpont foglalása',
    'hero.scopeLabel': 'Fókusz',
    'hero.scopeValue': 'Gyártás és ipari működés',
    'hero.preparedLabel': 'Praxis',
    'hero.preparedValue': 'Csomor Bence, alapító',
    'hero.basisLabel': 'Bizonyíték',
    'hero.basisValue': 'Három esettanulmány, nyilvános forráskóddal',

    'proof.heading': 'Mért eredmények',
    'proof.note': 'Az alábbi számok mind a mellettük hivatkozott esettanulmányból származnak. Egyik sem becslés.',
    'proof.recall.value': '96%',
    'proof.recall.label': 'meghibásodások felismerési aránya a tesztadatokon',
    'proof.recall.source': 'Prediktív karbantartási modell',
    'proof.accuracy.value': '99,27%',
    'proof.accuracy.label': 'a legjobb modell pontossága kézzel írt számjegyek felismerésében',
    'proof.accuracy.source': 'Számjegyfelismerési kutatás',
    'proof.experience.value': '4+',
    'proof.experience.label': 'év tapasztalat termelési és ipari adatokkal',
    'proof.experience.source': 'Eddigi tapasztalat',
    'proof.repos.value': '3',
    'proof.repos.label': 'esettanulmány nyilvános forráskóddal publikálva',
    'proof.repos.source': 'github.com/AnomInsight',

    'credentials.item1.title': '4+ év',
    'credentials.item1.text': 'Termelési és ipari adatok elemzésében szerzett tapasztalat',
    'credentials.item2.title': 'Ipari fókusz',
    'credentials.item2.text': 'Gyártási folyamatok adatalapú elemzése',
    'credentials.item3.title': 'Igazolt eredmények',
    'credentials.item3.text': 'Valós esettanulmányok mérhető eredményekkel, GitHubon publikálva',
    'credentials.item4.title': 'Folyamatos fejlesztés',
    'credentials.item4.text': 'Új analitikai megoldások folyamatos fejlesztése',

    'problem.title': 'A legtöbb cégnél van adat — de nincs tisztánlátás',
    'problem.text': 'A vállalatok naponta nagy mennyiségű adatot gyűjtenek, mégis nehezen alakítják át ezeket valóban hasznos, döntést támogató információvá. A hibák, az eltérések és a rejtett mintázatok gyakran észrevétlenek maradnak.',
    'problem.issue1': 'Váratlan leállások',
    'problem.issue1.detail': 'A gépek előjel nélkül meghibásodhatnak, és leállhat a termelés a műszak közben.',
    'problem.issue2': 'Hatékonysági problémákból eredő bevételkiesés',
    'problem.issue2.detail': 'A selejt és az újramunkálás rejtve marad, mert senki sem méri őket.',
    'problem.issue3': 'Pontatlan előrejelzés',
    'problem.issue3.detail': 'A tervezés a tavalyi táblázatra és megérzésre épül.',
    'problem.issue4': 'Lassú döntéshozatal',
    'problem.issue4.detail': 'Egyetlen szám előállítása három napba és két ember munkájába kerül.',

    'solution.title': 'A nyers adatokból döntést támogató információt készítek',
    'solution.text': 'Elemzem az adataidat, és átlátható, interaktív formában mutatom meg a bennük rejlő összefüggéseket, hogy gyorsabb és megalapozottabb döntéseket hozhass.',
    'solution.feature1': 'Adatmérnökség',
    'solution.feature2': 'Gépi tanulás',
    'solution.feature3': 'Vizualizáció',
    'solution.feature4': 'Prediktív analitika',

    'services.heading': 'Fő szolgáltatások',
    'services.subtitle': 'A legtöbb együttműködés itt kezdődik.',
    'services.cta': 'Ingyenes adataudit kérése',
    'services.card1.title': 'Adataudit és minőségértékelés',
    'services.card1.text': 'Átnézem az adathalmazaidat, és azonosítom a hiányzó értékeket, az ellentmondásokat és a szerkezeti hibákat.',
    'services.card2.title': 'Interaktív dashboardok',
    'services.card2.text': 'Egyedi dashboardok valós idejű diagramokkal és KPI-okkal, hogy átlásd az üzleti teljesítményt.',
    'services.card3.title': 'Automatizált riportálás',
    'services.card3.text': 'Ütemezett PDF- vagy e-mail-riportok a legfontosabb megállapításokkal és mutatókkal.',

    'advanced.title': 'Haladó analitika',
    'advanced.subtitle': 'Kérésre elérhető',
    'advanced.card1.title': 'Anomáliafelismerés',
    'advanced.card1.text': 'Automatikusan felismeri a szokatlan mintázatokat a működési vagy üzleti adataidban.',
    'advanced.card2.title': 'Előrejelző modellek',
    'advanced.card2.text': 'Előre jelzi az értékesítés, a termelés vagy a működési mutatók várható alakulását.',
    'advanced.card3.title': 'Prediktív karbantartás',
    'advanced.card3.text': 'Történeti és valós idejű adatokból jelzi a várható meghibásodásokat, mielőtt bekövetkeznének.',

    'portfolio.heading': 'Kiemelt projektek',
    'portfolio.subtitle': 'Valódi projektek, valós eredményekkel és nyilvános forráskóddal.',
    'portfolio.note': 'Minden projekt a nyilvános GitHub-repójára mutat, így magad is megnézheted a munkát.',
    'portfolio.statusFiltersTitle': 'Szűrés státusz szerint',
    'portfolio.filtersTitle': 'Szűrés típus szerint',
    'portfolio.filtersAria': 'Projekttípus-szűrők, egy vagy több típus választható',
    'portfolio.statusFiltersAria': 'Projektstátusz-szűrők, egy vagy több választható',
    'portfolio.statsAria': 'Portfólió kiemelt számok',
    'portfolio.trackAria': 'Portfólió projektek',
    'portfolio.navAria': 'Portfólió navigáció',
    'portfolio.navPrev': 'Előző projekt',
    'portfolio.navNext': 'Következő projekt',
    'portfolio.navDotsAria': 'Projekt oldalak',
    'portfolio.filterAll': 'Összes',
    'portfolio.clearAllFilters': 'Szűrők törlése',
    'portfolio.empty': 'Ezekkel a szűrőkkel még nincs találat.',
    'portfolio.expand': 'Teljes áttekintés elolvasása',
    'portfolio.collapse': 'Áttekintés bezárása',
    'portfolio.githubLabel': 'Forráskód megtekintése GitHubon',
    'portfolio.githubButton': 'Megtekintés GitHubon',
    'portfolio.detailsClose': 'Bezárás',
    'portfolio.metaPrefix': 'Típusok',
    'portfolio.focusHint': 'Kattints egy kártyára a részletek megtekintéséhez.',
    'portfolio.navDotLabel': 'Ugrás a(z) {n}. projekthez',
    'portfolio.statLabelProjects': 'Publikált esettanulmányok',
    'portfolio.statLabelIndustries': 'Lefedett iparágak',
    'portfolio.statLabelRepos': 'Nyilvános repók',
    'portfolio.ctaText': 'Hasonló kihívással nézel szembe a saját működésedben?',
    'portfolio.ctaButton': 'Beszéljünk',

    'method.title': 'Hogyan működik',
    'method.subtitle': 'Négy lépés a nyers adatoktól a megalapozott döntésig.',
    'method.step1.title': 'Adatbevitel',
    'method.step1.text': 'Töltsd fel az Excel-fájlt, vagy csatlakoztasd az adatbázist (SQL / API).',
    'method.step2.title': 'Elemzés',
    'method.step2.text': 'Feldolgozom és megtisztítom az adatokat fejlett elemzési módszerekkel és gépi tanulási modellekkel.',
    'method.step3.title': 'Eredmények',
    'method.step3.text': 'Irányítópultokat, riportokat és konkrét javaslatokat kapsz.',
    'method.step4.title': 'Folyamatos fejlesztés',
    'method.step4.text': 'Opcionális folyamatos monitorozás és modellfrissítés.',

    'usecases.title': 'Kinek szól',
    'usecases.subtitle': 'A munka a gyártásban kezdődött. A módszerek más iparágakban is alkalmazhatók.',
    'usecases.item1': 'Gyártó vállalatok',
    'usecases.item2': 'Logisztikai és ellátási lánccal foglalkozó vállalatok',
    'usecases.item3': 'E-kereskedelmi cégek',
    'usecases.item4': 'Energetika és közművek',
    'usecases.item5': 'Bármely adatvezérelt szervezet',

    'value.title': 'Mit nyersz vele',
    'value.item1': 'Megalapozottabb döntések',
    'value.item2': 'Alacsonyabb működési költség',
    'value.item3': 'A problémák korai felismerése',
    'value.item4': 'Átláthatóbb kép az üzleti teljesítményről',
    'value.item5': 'Adatvezérelt stratégia találgatás helyett',

    'roadmap.title': 'Folyamatosan bővülő szolgáltatások',
    'roadmap.subtitle': 'Folyamatosan bővítem az elérhető szolgáltatásokat és megoldásokat.',
    'roadmap.available': 'Jelenleg elérhető',
    'roadmap.developing': 'Fejlesztés alatt',
    'roadmap.item1': 'Adataudit',
    'roadmap.item2': 'Irányítópultok',
    'roadmap.item3': 'Automatizált riportálás',
    'roadmap.item4': 'Valós idejű anomáliafelismerés',
    'roadmap.item5': 'Prediktív analitika',
    'roadmap.item6': 'API-integrációk (SQL, ERP, IoT)',

    'about.title': 'Kivel dolgozol együtt',
    'about.name': 'Csomor Bence',
    'about.role': 'Alapító és data scientist',
    'about.bio1': 'Az AnomInsight egyszemélyes vállalkozás. Minden auditot, modellt és dashboardot én készítek és adok át, így közvetlenül azzal dolgozol, aki a munkát végzi.',
    'about.bio2': 'Több mint négy éve dolgozom termelési és ipari adatokkal, és publikálom, amit építek: az oldalon szereplő minden esettanulmány egy nyilvános repóra mutat, amelyeket elolvashatsz, lefuttathatsz és saját magad is értékelhetsz.',
    'about.linkedin': 'LinkedIn-profil',
    'about.github': 'GitHub-szervezet',
    'about.initials': 'CS',

    'finalcta.title': 'Mit tartalmaz az ingyenes adataudit',
    'finalcta.text': 'Gyors, kötelezettségmentes betekintés az adataidba, mielőtt bármilyen együttműködés mellett döntenél.',
    'finalcta.item1': 'Adatminőség-ellenőrzés: hiányzó értékek, ellentmondások és szerkezeti hibák',
    'finalcta.item2': 'Rövid írásos összefoglaló a fő megállapításokról és a gyorsan megvalósítható fejlesztési lehetőségekről',
    'finalcta.item3': 'Egy utólagos egyeztetés, amelyen közösen átbeszéljük az eredményeket',
    'finalcta.note': 'Hosszú távú elköteleződés nélkül.',
    'finalcta.cta': 'Ingyenes adataudit kérése',

    'contact.heading': 'Lépj kapcsolatba velem',
    'contact.copy': 'Kérdésed van? Töltsd ki az űrlapot, és 24 órán belül válaszolok, vagy írj közvetlenül e-mailben.',
    'contact.emailLabel': 'E-mail',
    'contact.locationLabel': 'Helyszín',
    'contact.locationValue': 'Távoli együttműködés / világszerte',
    'contact.responseLabel': 'Válaszidő',
    'contact.responseValue': '24 órán belül',
    'contact.bookCallButton': 'Időpont foglalása',
    'contact.formHeading': 'Írj nekem üzenetet',
    'contact.formName': 'Név',
    'contact.formNamePlaceholder': 'A neved',
    'contact.formEmail': 'E-mail',
    'contact.formEmailPlaceholder': 'te@ceged.hu',
    'contact.formMessage': 'Üzenet',
    'contact.formMessagePlaceholder': 'Írd le, milyen adatokkal rendelkezel, és mit szeretnél megtudni belőlük',
    'contact.formSubmit': 'Üzenet küldése',
    'contact.formSending': 'Küldés…',
    'contact.formSuccess': 'Köszönöm — az üzeneted sikeresen elküldve. 24 órán belül válaszolok.',
    'contact.formError': 'Hiba történt. Kérlek írj közvetlenül a hello@anominsight.com címre.',

    'footer.tagline': 'MI-alapú adatelemzés modern vállalatoknak.',
    'footer.rights': 'Minden jog fenntartva.',
  },
};

// The three real case studies. Facts, metrics and repository links are taken
// verbatim from the baseline build — no claim here may be invented or inflated.
export const portfolioProjects = [
  {
    id: 'cnc-predictive-maintenance',
    kind: { en: 'Manufacturing', hu: 'Gyártás' },
    status: 'caseStudy',
    title: {
      en: 'Predictive maintenance for CNC operations',
      hu: 'Prediktív karbantartás CNC-üzemekhez',
    },
    description: {
      en: 'A machine learning model that watches CNC machine sensors and flags the ones likely to break down soon. In testing, it caught 96% of real failures before they happened.',
      hu: 'Gépi tanulási modell, amely a CNC-gépek szenzoradatait figyeli, és jelzi, mely gépeknél várható hamarosan meghibásodás. A tesztelés során a valós meghibásodások 96%-át még bekövetkezésük előtt felismerte.',
    },
    overview: {
      en: 'Unplanned breakdowns are costly on a 24/7 CNC production line, so this project builds an early-warning system for machine failure. It looks at real sensor readings, such as temperature, power draw, and torque, to flag machines likely to fail within the next day or two, before anything actually breaks. After comparing a few different approaches, I settled on a LightGBM model (a fast, tree-based machine learning method) tuned to catch as many real failures as possible: in testing it caught 96% of actual breakdowns, at the cost of roughly two false alarms for every real one it found. The idea isn\'t to replace maintenance engineers. It\'s to hand them a prioritized daily list so they can focus their attention where it matters, with the alert sensitivity adjustable to match how many false alarms the team can realistically handle.',
      hu: 'A váratlan leállások sokba kerülnek egy folyamatosan üzemelő CNC-gyártásban, ezért ez a projekt korai figyelmeztető rendszert épít a gépleállások előrejelzésére. A modell valós szenzoradatokat figyel, például hőmérsékletet, teljesítményfelvételt és nyomatékot, hogy jelezze, mely gépek állhatnak le a következő egy-két napban, még mielőtt bármi elromlana. Több módszer kipróbálása után egy LightGBM modell mellett döntöttem (ez egy gyors, fákra épülő gépi tanulási módszer), amelyet úgy hangoltam, hogy a lehető legtöbb valós meghibásodást elkapja: a tesztelés során az esetek 96%-ában időben jelzett, cserébe nagyjából két téves riasztás valódi meghibásodásonként. A cél nem az, hogy kiváltsa a karbantartó mérnököket, hanem hogy egy priorizált napi listát adjon a kezükbe, amelyre érdemes figyelniük. A riasztási küszöb pedig állítható, hogy illeszkedjen ahhoz, mennyi téves riasztást bír el a csapat.',
    },
    metrics: [
      {
        value: '96%',
        label: { en: 'of real failures caught in testing', hu: 'valós meghibásodás elkapva teszteléskor' },
      },
      {
        value: '~2:1',
        label: { en: 'false alarms per true catch', hu: 'téves riasztás valós találatonként' },
      },
      {
        value: 'LightGBM',
        label: { en: 'model selected after comparison', hu: 'modell összehasonlítás után kiválasztva' },
      },
    ],
    categories: ['predictiveMaintenance', 'anomalyDetection', 'decisionSupport'],
    // 02_Portfolio_Project is the ai4i2020 predictive-maintenance repo; 01 is the
    // MNIST one. The two were previously swapped here (and still are in the
    // untouched ORIGINAL reference copy).
    githubUrl: 'https://github.com/AnomInsight/02_Portfolio_Project',
  },
  {
    id: 'digit-classifier-mail-sorting',
    kind: { en: 'Logistics', hu: 'Logisztika' },
    status: 'caseStudy',
    title: {
      en: 'Handwritten digit classifier for mail sorting',
      hu: 'Kézzel írt számjegyek osztályozása levélválogatáshoz',
    },
    description: {
      en: 'Compared five different AI models for reading handwritten ZIP codes automatically. The best one, a neural network, got it right 99.27% of the time.',
      hu: 'Öt különböző MI-modellt hasonlítottam össze kézzel írt irányítószámok automatikus felismerésére. A legjobb, egy neurális háló, az esetek 99,27%-ában helyesen ismerte fel a számjegyeket.',
    },
    overview: {
      en: 'Sorting mail by handwritten ZIP code is slow and error-prone when done by hand at scale, so this project explores whether AI can take over that job reliably. Starting from a simple baseline and working up through logistic regression, random forests, and support vector machines, I landed on a convolutional neural network (a type of model built specifically for recognizing images), which correctly read digits 99.27% of the time. Beyond just accuracy, I checked which digits the model tends to confuse with each other, looked closely at its most confident mistakes, and tested how well it holds up against rotated, noisy, or poorly lit scans. The practical takeaway: send anything the model isn\'t confident about to a human for a second look, and keep monitoring its mistakes after it goes live.',
      hu: 'A kézzel írt irányítószámok kézi feldolgozása lassú és hibalehetőségekkel teli, ha nagy mennyiségű küldeményt kell feldolgozni. Ez a projekt azt vizsgálja, hogy egy MI megbízhatóan át tudja-e venni ezt a feladatot. Egy egyszerű alapmodellből kiindulva, logisztikus regresszión, random forest modellen és support vector machine (SVM) modelleken keresztül végül egy konvolúciós neurális hálónál kötöttem ki (ez egy kifejezetten képfelismerésre kitalált modelltípus), amely az esetek 99,27%-ában helyesen ismerte fel a számjegyeket. A pontosságon túl azt is megvizsgáltam, mely számjegyeket keveri össze a modell egymással, alaposan átnéztem azokat a hibás előrejelzéseket, amelyekben a modell a legbiztosabb volt, és teszteltem, hogyan teljesít elforgatott, zajos vagy rosszul megvilágított képeken. A gyakorlati tanulság: azokat az eseteket, amelyekben a modell bizonytalan, azt küldjük emberi ellenőrzésre, és élesben is érdemes folyamatosan figyelni a hibáit.',
    },
    metrics: [
      {
        value: '99.27%',
        label: { en: 'accuracy, best model (CNN)', hu: 'pontosság, legjobb modell (CNN)' },
      },
      {
        value: '5',
        label: { en: 'model families compared', hu: 'összehasonlított modellcsalád' },
      },
      {
        value: 'CNN',
        label: { en: 'architecture selected', hu: 'kiválasztott architektúra' },
      },
    ],
    categories: ['imageClassification', 'deepLearning', 'computerVision'],
    githubUrl: 'https://github.com/AnomInsight/01_Portfolio_Project',
  },
  {
    id: 'restaurant-ai-chatbot',
    kind: { en: 'Hospitality', hu: 'Vendéglátás' },
    status: 'caseStudy',
    title: {
      en: 'AI chatbot for restaurant ordering and support',
      hu: 'MI-chatbot éttermi rendeléshez és ügyfélszolgálathoz',
    },
    description: {
      en: 'An AI chat widget built for a demo pizzeria website that answers questions about the menu, hours, and orders. It is designed to stick to food that is actually on the menu.',
      hu: 'MI-alapú chatwidget egy demó pizzéria weboldalához, amely válaszol a menüvel, a nyitvatartással és a rendelésekkel kapcsolatos kérdésekre. Úgy készült, hogy csak a menüben ténylegesen szereplő ételekről beszéljen.',
    },
    overview: {
      en: 'Small businesses often lose customers simply because nobody\'s around to answer a quick question like "are you open right now?" or "what\'s your best-selling pizza?". This project shows how a lightweight AI chatbot can fill that gap. I built a demo pizzeria website with a chat widget powered by a fast large language model (via Groq), and kept it honest by only letting it talk about real menu items, prices, and hours pulled straight from the business\'s own data, which keeps it grounded and much less likely to make up a dish that doesn\'t exist. It remembers the conversation while you\'re chatting, keeps track of which items get ordered most, and includes basic safeguards like rate limiting and API key protection. The widget itself is just plain HTML, CSS, and JavaScript, so it can be dropped into almost any existing website.',
      hu: 'A kisvállalkozások gyakran veszítenek el ügyfeleket csak azért, mert senki sincs ott, hogy megválaszoljon egy egyszerű kérdést, mint például „nyitva vannak most?” vagy „melyik a legnépszerűbb pizzájuk?”. Ez a projekt azt mutatja be, hogyan tud egy könnyű MI-chatbot pótolni ezt a hiányt. Egy demó pizzéria weboldalt építettem egy chat widgettel, amely egy gyors nagy nyelvi modellre épül (Groq-on keresztül), és úgy állítottam be, hogy kizárólag a vállalkozás saját adataira, étlapjára, áraira és nyitvatartására támaszkodjon, ami sokkal kisebb eséllyel eredményez nem létező ételeket. A beszélgetés során figyelembe veszi a korábbi üzeneteket, nyomon követi, mely ételeket rendelik a leggyakrabban, és alapvető védelmi mechanizmusokat is alkalmaz, például a kérések számának korlátozását és az API-kulcs védelmét. Maga a widget egyszerű HTML, CSS és JavaScript, így szinte bármelyik meglévő weboldalba beilleszthető.',
    },
    metrics: [
      {
        value: 'Groq',
        label: { en: 'LLM provider behind the widget', hu: 'a widget mögötti LLM-szolgáltató' },
      },
      {
        value: 'Demo',
        label: { en: 'project, not a paying client', hu: 'projekt, nem fizető ügyfél' },
      },
      {
        value: 'HTML/CSS/JS',
        label: { en: 'drop-in, no framework needed', hu: 'beilleszthető, keretrendszer nélkül' },
      },
    ],
    categories: ['chatbot', 'llmIntegration', 'customerExperience'],
    githubUrl: 'https://github.com/AnomInsight/03_Portfolio_Project',
  },
];

export const portfolioCategoryLabels = {
  predictiveMaintenance: { en: 'Predictive maintenance', hu: 'Prediktív karbantartás' },
  anomalyDetection: { en: 'Anomaly detection', hu: 'Anomáliafelismerés' },
  decisionSupport: { en: 'Decision support', hu: 'Döntéstámogatás' },
  imageClassification: { en: 'Image classification', hu: 'Képosztályozás' },
  deepLearning: { en: 'Deep learning', hu: 'Mélytanulás' },
  computerVision: { en: 'Computer vision', hu: 'Számítógépes látás' },
  chatbot: { en: 'AI chatbot', hu: 'MI-chatbot' },
  llmIntegration: { en: 'LLM integration', hu: 'LLM-integráció' },
  customerExperience: { en: 'Customer experience', hu: 'Ügyfélélmény' },
};

export const portfolioStatusLabels = {
  live: { en: 'Live', hu: 'Aktív' },
  pilot: { en: 'Pilot', hu: 'Próbaüzem' },
  caseStudy: { en: 'Case study', hu: 'Esettanulmány' },
  prototype: { en: 'Prototype', hu: 'Prototípus' },
  workInProgress: { en: 'Work in progress', hu: 'Fejlesztés alatt' },
  ongoing: { en: 'Ongoing', hu: 'Folyamatban' },
  planned: { en: 'Planned', hu: 'Tervezett' },
  testing: { en: 'Testing', hu: 'Tesztelés alatt' },
};

export const getLabel = (dict, id, lang) => {
  const entry = dict[id];
  if (!entry) {
    return id;
  }
  return entry[lang] || entry.en;
};
