// Chrome labels specific to the Dossier direction. Product copy lives in
// ../../shared/content.js; only the words this layout invents belong here.

export const labels = {
  en: {
    // The shared hero heading is the baseline's marketing line. A report's
    // title page names its subject instead, and the industrial focus belongs
    // in the title rather than in a field below it.
    'b.hero.heading': 'Data audits and predictive models for industrial operations',
    'b.hero.copy': 'A one-person practice. I audit operational data, build the models that act on it, and publish every result with the source code behind it.',
    'b.form.submit': 'Request the audit',
    'b.form.heading': 'Request your free audit',
    'b.signature.practice': 'Practice',
    'b.signature.contact': 'Contact',
    'b.signature.signed': 'Signed',
    'b.contents': 'Contents',
    'b.toc.findings': 'Findings',
    'b.toc.scope': 'Scope',
    'b.toc.exhibits': 'Exhibits',
    'b.toc.method': 'Method',
    'b.toc.about': 'Practitioner',
    'b.toc.request': 'Request',
    'b.findings.colRef': 'Ref.',
    'b.findings.colFinding': 'Finding',
    'b.findings.colCost': 'What it costs you',
    'b.scope.disciplines': 'Disciplines',
    'b.scope.core': 'Core engagement',
    'b.scope.extended': 'Extended scope',
    'b.exhibit': 'Exhibit',
    'b.exhibit.repo': 'Repository',
    'b.exhibit.industry': 'Industry',
    'b.exhibit.status': 'Status',
    'b.exhibit.index': 'Index',
    'b.register.status': 'Status',
    'b.register.capability': 'Capability',
    'b.register.online': 'Available',
    'b.register.development': 'In development',
    'b.preparedBy': 'Prepared by',
    'b.signature': 'Signature',
    'b.colophon': 'Colophon',
    'b.audit.included': 'Included in the free audit',
    'b.contact.direct': 'Direct contact',
  },
  hu: {
    'b.hero.heading': 'Adataudit és prediktív modellek ipari üzemekhez',
    'b.hero.copy': 'Egyszemélyes praxis. Auditálom a működési adatokat, megépítem a rájuk épülő modelleket, és minden eredményt publikálok a mögötte álló forráskóddal együtt.',
    'b.form.submit': 'Audit kérése',
    'b.form.heading': 'Kérd az ingyenes auditot',
    'b.signature.practice': 'Praxis',
    'b.signature.contact': 'Elérhetőség',
    'b.signature.signed': 'Aláírás',
    'b.contents': 'Tartalom',
    'b.toc.findings': 'Megállapítások',
    'b.toc.scope': 'Terjedelem',
    'b.toc.exhibits': 'Mellékletek',
    'b.toc.method': 'Módszer',
    'b.toc.about': 'Szakértő',
    'b.toc.request': 'Igénylés',
    'b.findings.colRef': 'Az.',
    'b.findings.colFinding': 'Megállapítás',
    'b.findings.colCost': 'Mibe kerül',
    'b.scope.disciplines': 'Szakterületek',
    'b.scope.core': 'Alapmunka',
    'b.scope.extended': 'Bővített terjedelem',
    'b.exhibit': 'Melléklet',
    'b.exhibit.repo': 'Repó',
    'b.exhibit.industry': 'Iparág',
    'b.exhibit.status': 'Státusz',
    'b.exhibit.index': 'Index',
    'b.register.status': 'Státusz',
    'b.register.capability': 'Képesség',
    'b.register.online': 'Elérhető',
    'b.register.development': 'Fejlesztés alatt',
    'b.preparedBy': 'Készítette',
    'b.signature': 'Aláírás',
    'b.colophon': 'Impresszum',
    'b.audit.included': 'Az ingyenes audit tartalma',
    'b.contact.direct': 'Közvetlen elérés',
  },
};
