// Chrome labels specific to the Console direction. Product copy lives in
// ../../shared/content.js; only the words this layout invents belong here.

export const labels = {
  en: {
    // The shared hero heading is the baseline's marketing line. This direction
    // states the mechanism in the register its audience works in, and puts the
    // industrial case in the first sentence rather than in a field below it.
    'c.hero.heading': 'Catch the failure before it stops the line',
    'c.hero.copy': 'I read machine and process data for the patterns that run ahead of a stoppage, and put the result where the people who act on it will see it.',
    'c.form.submit': 'Submit request',
    'c.rail.title': 'Sections',
    'c.nav.overview': 'Overview',
    'c.nav.faults': 'Fault conditions',
    'c.nav.capabilities': 'Capabilities',
    'c.nav.log': 'Project log',
    'c.nav.sequence': 'Process',
    'c.nav.operator': 'Operator',
    'c.nav.contact': 'Request',
    'c.mod.readout': 'Measured results',
    'c.mod.faults': 'Fault conditions',
    'c.mod.disciplines': 'Disciplines',
    'c.mod.core': 'Core services',
    'c.mod.advanced': 'Advanced analytics',
    'c.mod.log': 'Project log',
    'c.mod.sequence': 'Process sequence',
    'c.mod.sectors': 'Applicable sectors',
    'c.mod.output': 'Output',
    'c.mod.register': 'Capability register',
    'c.mod.operator': 'Operator',
    'c.mod.request': 'Request channel',
    'c.mod.audit': 'Free audit contents',
    'c.col.value': 'Value',
    'c.col.reading': 'Reading',
    'c.col.source': 'Source',
    'c.status.available': 'Available',
    'c.status.development': 'In development',
    'c.status.request': 'On request',
    'c.log.open': 'Open record',
    'c.log.close': 'Close record',
    'c.log.record': 'Record',
    'c.log.industry': 'Industry',
    'c.log.status': 'Status',
    'c.log.overview': 'Full overview',
    'c.log.filtersOn': 'Filters active',
    'c.footer.status': 'Practice status',
    'c.footer.accepting': 'Accepting new engagements',
  },
  hu: {
    'c.hero.heading': 'Kapd el a hibát, mielőtt megállítja a sort',
    'c.hero.copy': 'A gép- és folyamatadatokban azokat a mintázatokat keresem, amelyek megelőzik a leállást, és oda teszem az eredményt, ahol látja az, aki lépni tud.',
    'c.form.submit': 'Kérés elküldése',
    'c.rail.title': 'Szekciók',
    'c.nav.overview': 'Áttekintés',
    'c.nav.faults': 'Hibajelenségek',
    'c.nav.capabilities': 'Képességek',
    'c.nav.log': 'Projektnapló',
    'c.nav.sequence': 'Folyamat',
    'c.nav.operator': 'Szakértő',
    'c.nav.contact': 'Igénylés',
    'c.mod.readout': 'Mért eredmények',
    'c.mod.faults': 'Hibajelenségek',
    'c.mod.disciplines': 'Szakterületek',
    'c.mod.core': 'Alapszolgáltatások',
    'c.mod.advanced': 'Haladó analitika',
    'c.mod.log': 'Projektnapló',
    'c.mod.sequence': 'Folyamatlépések',
    'c.mod.sectors': 'Érintett iparágak',
    'c.mod.output': 'Eredmény',
    'c.mod.register': 'Képességnyilvántartás',
    'c.mod.operator': 'Szakértő',
    'c.mod.request': 'Kapcsolatfelvétel',
    'c.mod.audit': 'Az ingyenes audit tartalma',
    'c.col.value': 'Érték',
    'c.col.reading': 'Mérés',
    'c.col.source': 'Forrás',
    'c.status.available': 'Elérhető',
    'c.status.development': 'Fejlesztés alatt',
    'c.status.request': 'Kérésre',
    'c.log.open': 'Rekord megnyitása',
    'c.log.close': 'Rekord bezárása',
    'c.log.record': 'Rekord',
    'c.log.industry': 'Iparág',
    'c.log.status': 'Státusz',
    'c.log.overview': 'Teljes áttekintés',
    'c.log.filtersOn': 'Aktív szűrők',
    'c.footer.status': 'A praxis állapota',
    'c.footer.accepting': 'Új együttműködéseket fogadok',
  },
};
